---
phdz_sys_linux_baseline_default_packages:
  - binfmt-support # Cross platform support for podman
  - build-essential
  - ca-certificates
  - curl
  - git
  - gnupg
  - gpg-agent
  - less
  - makepasswd
  - qemu-user-static # Cross platform support for podman
  - sudo
  - tmux
  - tree
  - uidmap # Needed by Ansible/podman
  - unzip
  - vim
  - wget
  - whois # provides mkpasswd for Argon2 password hashing
  - yq
  - zip
  - zsh

phdz_sys_linux_baseline_packages: []
phdz_sys_linux_baseline_upgrade: false
phdz_sys_linux_baseline_services: []
phdz_sys_linux_baseline_default_alternatives:
  editor: /usr/bin/vim.basic
  vi: /usr/bin/vim.basic
  view: /usr/bin/vim.basic
phdz_sys_linux_baseline_alternatives: {}
