#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset

INSTALL_DIR=${GITHUB_WORKSPACE:-$PWD}

echo "++ INFO - Setting up the project in: $INSTALL_DIR"
if [ -e "${INSTALL_DIR}/.venv" ]; then
  echo "++ ERROR - Already exists: ${INSTALL_DIR}/.venv"
  exit 1
fi

set -o xtrace

/usr/bin/python3 -m venv "${INSTALL_DIR}/.venv"
# shellcheck disable=SC1091  # File needs to be generated by venv.
source "${INSTALL_DIR}/.venv/bin/activate"
pip3 install --upgrade --upgrade-strategy eager pip setuptools wheel
pip3 install ansible ansible-lint 'molecule[docker,lint]'

which vagrant > /dev/null \
    && pip3 install molecule-vagrant python-vagrant

which ansible ansible-lint molecule yamllint ansible-galaxy
ansible --version
ansible-lint --version
molecule --version
yamllint --version
ansible-galaxy install -r requirements.yml
