---
- hosts: all
  tasks:
    - name: Place holder...
      debug:
        msg: place holder...

- hosts: all
  roles:
    # - role: macos-desktop
    #   when: ansible_os_family == 'Darwin'
    - role: lafarer.osx-defaults
      when: ansible_os_family == 'Darwin'
  vars_files:
    - ['vars/home-{{ ansible_os_family }}.yaml', vars/home-defaults.yaml]
#     - vars/home-all.yaml
...
