---
- hosts: all
  roles:
    - avinode.devenv.baseline
    - avinode.devenv.packages
    - avinode.devenv.pyvenv_apps
    #- avinode.devenv.install_terraform_versions
    #- avinode.devenv.install_kubectl_versions
    #- avinode.devenv.install_helm_versions
  tasks:
    - name: Install packages only available on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: Load packages-ubuntu.yaml
          ansible.builtin.include_vars:
            file: vars/packages-ubuntu.yaml
        - name: Install Ubuntu packages
          ansible.builtin.include_role:
            name: avinode.devenv.packages
    - name: Install packages only available on Debian
      when: ansible_distribution == 'Debian'
      block:
        - name: Load packages-debian.yaml
          ansible.builtin.include_vars:
            file: vars/packages-debian.yaml
        - name: Install Debian packages
          ansible.builtin.include_role:
            name: avinode.devenv.packages

  vars_files:
    - ['vars/os-{{ ansible_os_family }}.yaml', vars/os-defaults.yaml]
    - vars/all.yaml
    #- vars/simple-variants.yaml

# - hosts: workstation
#   roles:
#     - avinode.devenv.packages
#   vars_files:
#     - ['vars/os-{{ ansible_os_family }}.yaml', vars/os-defaults.yaml]
#     - vars/workstation.yaml
...
