---
- hosts: all
  roles:
    - avinode.devenv.baseline
    - avinode.devenv.packages
    - avinode.devenv.pyvenv_apps
    #- avinode.devenv.install_terraform_versions
    #- avinode.devenv.install_kubectl_versions
    #- avinode.devenv.install_helm_versions
  vars_files:
    - ['vars/os-{{ ansible_os_family }}.yaml', vars/os-defaults.yaml]
    - vars/all.yaml
    #- vars/simple-variants.yaml

# - hosts: workstation
#   roles:
#     - avinode.devenv.packages
#   vars_files:
#     - ['vars/os-{{ ansible_os_family }}.yaml', vars/os-defaults.yaml]
#     - vars/workstation.yaml
...
