---
# -----------------------------------------------------------------------------
# User level configuration workstation
# -----------------------------------------------------------------------------
- name: User level configuration workstation (must not run as sudo)
  become: false
  gather_facts: true
  hosts:
    - dev_workstation
  vars:
    ansible_user: "{{ phdz_sys_dev_user_name }}"
    ansible_ssh_common_args: >-
      {{ phdz_base_ansible_ssh_common_args }}
      -o IdentityFile=~/.ssh/id_ed25519

    phdz_defaults_use_become: false
    _phdz_private_varfile: >-
      {{ lookup('env', 'HOME') + '/.private/ansible/dev-workstation/vars/baseline.yaml' }}

    # TODO:
    #   - move into group_vars/?
    #   - make comment dynamic,pulled from regex?
    #   - drop local SSH key from `make shell-user`
    #
    # ^\s*([^\s]+)\s+([^\s]+)(?:\s+(.+))?\s*$
    #
    _phdz_ssh_keys_authorized_keys:
      - key: >-
          {{
            lookup('file', phdz_ssh_public_key_file)
              | trim
          }}
        comment: foo-hoo
      - key: >-
          {{
            lookup(
              'file',
              lookup('env', 'HOME') + '/.ssh/id_ed25519.pub'
            )
              | trim
          }}
        comment: foo-bar

    phdz_ssh_keys_authorized_keys: >-
      {{
        phdz_ssh_keys_authorized_keys_extras | default([])
          + _phdz_ssh_keys_authorized_keys
      }}

  pre_tasks:
    - name: Show which user will be used
      ansible.builtin.debug:
        msg: "Running as {{ ansible_user }}"

    - name: Fail if vars file is missing
      ansible.builtin.stat:
        path: "{{ _phdz_private_varfile }}"
      delegate_to: localhost
      register: _phdz_private_varfile_status

    - name: Abort if vars file not found
      ansible.builtin.fail:
        msg: "Required vars file not found: {{ _phdz_private_varfile }}"
      when: not _phdz_private_varfile_status.stat.exists

  vars_files:
    - "{{ _phdz_private_varfile }}"

  roles:
    - phdz_ssh_keys # Needed by phdz_homeshick
    - phdz_homeshick
    - phdz_gpg_keys
    - phdz_nix_home_manager
    - phdz_secure_home # Should almost always be last
