---
collections:
  #- name: https://github.com/pedrohdz-scrap/ansible-collection-devenv.git
  - name: https://github.com/Avinode/ansible-collection-devenv.git
    type: git
    version: main
    #version: pyenv
  # Pull latest version of `community.docker`
  - name: community.docker
...
