---
collections:
  #- name: https://github.com/pedrohdz-scrap/ansible-collection-devenv.git
  - name: https://github.com/Avinode/ansible-collection-devenv.git
    type: git
    version: main
    #version: pyenv
roles:
  - name: lafarer.osx-defaults
    scm: git
    src: https://github.com/pedrohdz-scrap/ansible-role-osx-defaults.git
    version: unstep-on-vars
...
