---
- name: Test user configuration roles
  become: true
  become_user: "{{ phdz_sys_dev_user_name }}" # ansible_user does not work with nix
  gather_facts: true
  hosts: all
  vars:
    phdz_defaults_use_become: false # Should not be needed, but just for in case
  roles:
    - phdz_homeshick
    - phdz_gpg_keys
    - phdz_ssh_keys
    - phdz_nix_home_manager
    - phdz_secure_home # Should almost always be last
