---
# TODO - Test at the playbook level at some point.
# - name: User home level playbook under test
#   become: true
#   become_user: tester
#   ansible.builtin.import_playbook: ../../playbook-home.yaml
#   tags:
#     - molecule-home

- name: Test user configuration roles
  become: true
  become_user: tester
  gather_facts: true
  hosts: all
  roles:
    - phdz_homeshick
    - phdz_secure_home
    - phdz_gpg_keys
    - phdz_ssh_keys

...
