---
- name: Test user configuration roles
  become: true
  become_user: "{{ phdz_sys_dev_user_name }}" # ansible_user does not work with nix
  gather_facts: true
  hosts: all

  vars:
    phdz_defaults_use_become: false # Should not be needed, but just for in case
    phdz_nix_home_manager_hostname: >-
      {{ lookup('env', 'PHDZ_NIX_HOME_MANAGER_HOSTNAME') | default(ansible_hostname, true) }}

  roles:
    - phdz_ssh_keys # Needed by phdz_homeshick
    - phdz_homeshick
    - phdz_gpg_keys
    - phdz_nix_home_manager
    - phdz_secure_home # Should almost always be last
