---
driver:
  name: podman

platforms:
  # For more pre-baked images:
  # - https://ansible.jeffgeerling.com/
  - name: ubuntu2404
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    image: 'docker.io/geerlingguy/docker-ubuntu2404-ansible:latest'
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

dependency:
  name: galaxy
  enabled: false

provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/.ansible
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles:${MOLECULE_PROJECT_DIRECTORY}/.ansible/roles
    # ANSIBLE_FORCE_COLOR: 'true'
    # PY_COLORS: 'true'
  inventory:
    group_vars:
      all:
        phdz_homeshick_castles:
          - https://github.com/pedrohdz/dotfiles-vim.git
          - https://github.com/pedrohdz/dotfiles-zsh.git
  # config_options:
  #   defaults:
  #     stdout_callback: debug
  #     stderr_callback: debug

verifier:
  name: ansible

lint: |
  set -e
  yamllint --format=colored .
  ansible-lint --force-color

...
