---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu2004
    box: ubuntu/focal64
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: true  # `yes`?
      synced_folder: true
    provision: no
  - name: debian10
    box: debian/contrib-buster64
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: true
      synced_folder: true
    provision: no
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/.ansible
    ANSIBLE_FORCE_COLOR: 'true'
    PY_COLORS: 'true'
  config_options:
    defaults:
      stdout_callback: debug
      stderr_callback: debug
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
