---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # For more pre-baked images:
  # - https://hub.docker.com/search?q=geerlingguy%2Fdocker&type=image
  - name: ubuntu2004
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  # - name: ubuntu1804
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  - name: debian10
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  # - name: debian9
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/.ansible
    ANSIBLE_FORCE_COLOR: 'true'
    PY_COLORS: 'true'
  config_options:
    defaults:
      stdout_callback: debug
      stderr_callback: debug
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
