---
driver:
  name: docker

platforms:
  # For more pre-baked images:
  # - https://hub.docker.com/search?q=geerlingguy%2Fdocker&type=image
  - name: ubuntu2404
    image: 'geerlingguy/docker-ubuntu2404-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  - name: ubuntu2204
    image: 'geerlingguy/docker-ubuntu2204-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  - name: debian12
    image: 'geerlingguy/docker-debian12-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  - name: debian11
    image: 'geerlingguy/docker-debian11-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

dependency:
  name: galaxy
  enabled: false

provisioner:
  name: ansible
  env:
    # ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/.ansible
    ANSIBLE_COLLECTIONS_PATH: '/opt/avinode/workspace/dev/src-oss/ansible-collection-devenv:${MOLECULE_PROJECT_DIRECTORY}/.ansible'
    ANSIBLE_FORCE_COLOR: 'true'
    PY_COLORS: 'true'
  config_options:
    defaults:
      stdout_callback: debug
      stderr_callback: debug

verifier:
  name: ansible

lint: |
  set -e
  yamllint --format=colored .
  ansible-lint --force-color

...
