---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Assert Nix is installed (binary exists)
      ansible.builtin.stat:
        path: /nix/var/nix/profiles/default/bin/nix
      register: _phdz_nix_verify_stat

    - name: Assert Nix binary is present
      ansible.builtin.assert:
        that:
          - _phdz_nix_verify_stat.stat.exists
...
