#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset

#------------------------------------------------------------------------------
# Configure & sanity check
#------------------------------------------------------------------------------
PROJECT_DIR="$(builtin cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." &> /dev/null && pwd)"
VENV_DIR_NAME=${VENV_DIR_NAME:-.venv}
VENV_DIR=${PROJECT_DIR}/${VENV_DIR_NAME}

echo "++ INFO - Setting up the project in: $PROJECT_DIR ($VENV_DIR_NAME)"

if [ -e "${VENV_DIR}" ]; then
  echo "++ ERROR - Already exists: ${VENV_DIR}"
  exit 1
fi

#------------------------------------------------------------------------------
# Pick Python version
#------------------------------------------------------------------------------
PYTHON=$(command -v python)

set -o xtrace


#------------------------------------------------------------------------------
# Setup Python venv
#------------------------------------------------------------------------------
"$PYTHON" -m venv "${VENV_DIR}"

set +o xtrace
# shellcheck disable=SC1091  # File needs to be generated by venv.
source "${VENV_DIR}/bin/activate"
set -o xtrace
pip3 install --upgrade --upgrade-strategy eager pip setuptools wheel
pip3 install --requirement "${PROJECT_DIR}/requirements.txt"


#------------------------------------------------------------------------------
# Record versions
#------------------------------------------------------------------------------
which "$PYTHON"
"$PYTHON" --version

which ansible ansible-lint molecule yamllint ansible-galaxy
ansible --version
ansible-galaxy --version
ansible-lint --version
molecule --version
yamllint --version
pip3 freeze


#------------------------------------------------------------------------------
# Ansible setup
#------------------------------------------------------------------------------
ansible-galaxy install -r requirements.yml
