---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # For more pre-baked images:
  # - https://hub.docker.com/search?q=geerlingguy%2Fdocker&type=image
  - name: ubuntu2204
    image: 'geerlingguy/docker-ubuntu2204-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  - name: debian11
    image: 'geerlingguy/docker-debian11-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/.ansible
    ANSIBLE_FORCE_COLOR: 'true'
    PY_COLORS: 'true'
  config_options:
    defaults:
      stdout_callback: debug
      stderr_callback: debug
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
