---
- name: Ensure homeshick repos directory exists
  ansible.builtin.file:
    mode: '0700'
    path: '{{ phdz_homeshick_repo_dir }}'
    state: directory

# This directory will likely be created elsewhere as well, but I think this
# should be harmless.
- name: Ensure secure directory for SSH ControlPath
  ansible.builtin.file:
    mode: '0700'
    path: '{{ phdz_homeshick_ssh_sockets_dir }}'
    state: directory

- name: Ensure homeshick is cloned
  ansible.builtin.git:
    repo: '{{ phdz_homeshick_repo_url }}'
    dest: '{{ phdz_homeshick_repo_dir }}/homeshick'
    version: '{{ phdz_homeshick_version }}'
    update: false
  notify: phdz_homeshick | on-clone-updated

- name: Wait for operator confirmation (SSH key auth may be required)
  ansible.builtin.pause:
    prompt: 'Press Enter once ready (SSH key authorization may be needed)...'
  when: phdz_homeshick_wait_for_ssh_key_auth | bool

# TODO - ControlPath might cause problems if a castle in phdz_homeshick_castles
# spans across Git account on the same server.  This will make for a single
# socket used across accounts and create authorization issues.  Look into
# fixing this.
- name: Ensure homeshick castles are cloned
  ansible.builtin.git: # noqa: latest[git]
    repo: '{{ item }}'
    dest: '{{ phdz_homeshick_repo_dir }}/{{ _target_dir }}'
    update: false
    ssh_opts: '{{ phdz_homeshick_ssh_opts }}'
  loop: '{{ phdz_homeshick_castles }}'
  when: phdz_homeshick_castles | length > 0
  notify: phdz_homeshick | on-clone-updated
  vars:
    _target_dir: >-
      {{ (item | regex_replace('.*/', '')) | regex_replace('\.git$', '') }}

- name: Flush pending handlers
  ansible.builtin.meta: flush_handlers
